name: Build and Package

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.406'

      - name: Pack PdfForge NuGet package
        run: |
          cd PdfForge
          dotnet pack --configuration Release --output ../nupkgs -p:NuspecFile=./PdfForge.nuspec

      - name: Pack PdfForge.Avalonia NuGet package
        run: |
          cd PdfForge.Avalonia
          dotnet pack --configuration Release --output ../nupkgs -p:NuspecFile=./PdfForge.Avalonia.nuspec
      
      - name: Upload Nuget Packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: nupkgs/

      - name: Publish PdfForge to NuGet.org
        run: |
          dotnet nuget push ./nupkgs/PdfForge.[0-9]*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Publish PdfForge.Avalonia to NuGet.org
        run: |
          dotnet nuget push ./nupkgs/PdfForge.Avalonia.[0-9]*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json