name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      # Установка .NET SDK для использования dotnet CLI
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.401'

      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libpoppler-glib-dev libcairo2-dev libglib2.0-dev

      - name: Build for Linux
        run: |
          cd PdfForge.Rust
          rustup target add x86_64-unknown-linux-gnu
          export RUSTFLAGS="-L /usr/lib/x86_64-linux-gnu -lpoppler-glib -lcairo -lglib-2.0 -lgobject-2.0"
          cargo build --release --target=x86_64-unknown-linux-gnu

      - name: Copy dependent .so libraries to NuGet folder
        run: |
          cd PdfForge.Rust/target/x86_64-unknown-linux-gnu
          mkdir -p ../../PdfForge/runtimes/linux-x64/native
          ldd release/libpdf_forge.so | grep "=> /" | awk '{print $3}' | grep -E "(poppler|cairo|glib|gobject|gio|jpeg|tiff|openjp2|lcms2|nss)" | xargs -I '{}' cp -v '{}' ../../PdfForge/runtimes/linux-x64/native/
          cp release/libpdf_forge.so ../../PdfForge/runtimes/linux-x64/native/
      
      - name: Add .so to nuspec
        run: |
          cd PdfForge
          ./gen_nuspec.sh

      - name: Pack the NuGet package
        run: |
          cd PdfForge
          dotnet pack --runtime linux-x64 --configuration Release --output ./nupkgs -p:NuspecFile=./PdfForge.nuspec
          

      - name: Upload NuGet package
        uses: actions/upload-artifact@v3
        with:
          name: PdfForge-nuget-package
          path: PdfForge/nupkgs/*.nupkg
